sequenceDiagram
    participant browser
    participant server

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server

    Note right of browser: The POST request contains the new note as JSON data

    server-->>browser: 201 Created
    deactivate server

    Note right of browser: Previously loaded JS pushes the note into the array of notes

